FROM node:latest

MAINTAINER 'Loris Baeriswyl' 'loris.baeriswyl@liip.ch'

WORKDIR /app

COPY app.js /app/app.js
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY services/ /app/services

RUN npm install

ENTRYPOINT ["/bin/npm" , "start"]